version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: rexpense_pg_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rexpense
      POSTGRES_USER: rexpense
      POSTGRES_PASSWORD: rexpense
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: